# Travis CI configuration
sudo: true
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - sudo pecl install gmp
  - sudo pecl install bcmath

script: phpunit
